export const TRANSLATE_ESP: any = {
	'incidents': 'Incidentes',
	'date': 'Fecha',
	'add incident': 'Agregar incidente',
	'all centers': 'Todos los centros',
	'centers': 'Centros',
	'add project': 'Agregar proyecto',
	'production Company': 'Compañia de producción',
	'project': 'Proyecto',
	'season': 'Temporada',
	'center': 'Centro',
	'location': 'Locación',
	'users': 'Usuarios',
	'open inc': 'Inc. abiertos',
	'closed inc': 'Inc. cerrados',
	'no data found': 'Datos no encontrados',
	'merge': 'Unir',
	'project name': 'Nombre de proyecto',
	'abbreviation': 'Abreviación',
	'add': 'Añadir',
	'delete': 'Eliminar',
	'email': 'Correo',
	'save': 'Guardar',
	'project users': 'Usuarios del proyecto',
	'search': 'Buscar',
	'insert': 'Insertar',
	'projects': 'Proyectos',
	'all statuses': 'Todos los estados',
	'all types': 'Todos los tipos',
	'all projects': 'Todos los proyectos',
	'clear': 'Limpiar',
	'reference': 'Referencia',
	'status': 'Estados',
	'incident type': 'Tipo de incidente',
	'not assigned': 'No asignado',
	'incident': 'Incidente',
	'comments': 'Comentarios',
	'edit incident': 'Editar incidente',
	'select option': 'Seleccionar opción',
	'how do you want to report the incident?': '¿Cómo quieres reportar el incidente?',
	'anonymous': 'Anónimo',
	'i want to identify myself': 'Quiero identificarme',
	'do you authorize us to send messages to your email that maybe required for the investigation?': '¿Nos autoriza a enviar mensajes a su correo electrónico que tal vez sean necesarios para la investigación?',
	'yes': 'Si',
	'confirm email': 'Confirmar email',
	'first name': 'Primer nombre',
	'name': 'Nombre',
	'last name': 'Apellido',
	'country': 'País',
	'phone number': 'Número de telefono',
	'number': 'Número',
	'select issue type': 'Seleccione el tipo de problema',
	'what is the production?': '¿Cuál es la producción?',
	'production Name': 'Nombre de producción',
	'please describe the incident': 'Por favor describa el incidente',
	'description': 'Descripción',
	'people involved in the incident': 'Personas involucradas en el incidente',
	'people': 'Personas',
	'date and location of the incident': 'Fecha y locación del incidente',
	'has this incident happened more than once?': '¿Este incidente ha ocurrido más de una vez?',
	'please provide the details': 'Por favor proporcione los detalles',
	'details': 'Detalles',
	'have you discussed this incident with your manager or production supervisor?': '¿Ha discutido este incidente con su gerente o supervisor de producción?',
	'who did you report this incident to?': '¿A quién le reportó este incidente?',
	'who': 'Quién',
	'cancel': 'Cancelar',
	'under review': 'En revisión',
	'on': 'En',
	'response': 'Respuesta',
	'date report': 'Fecha de reporte',
	'method': 'Método',
	'reporter': 'Reporte',
	'notifications': 'Notificaciones',
	'position on production': 'Posición en producción',
	'date incident': 'Fecha de incidente',
	'location incident': 'Locación de incidente',
	'repeated incident': 'Incidente repetido',
	'discussed incident with manager or supervisor': 'Incidente discutido con el administrador o supervisor',
	'responses': 'Respuestas',
	'write your response': 'Escriba su respuesta',
	'admin module': 'Módulo de administrador',
	'login with google acount': 'Inicia sesión con la cuenta de Google',
	'login with other email': 'Inicia sesión con otro correo',
	'new project': 'Nuevo proyecto',
	'token successfully generated': 'Token generado con éxito',
	'please check your email': 'Por favor revise su correo electrónico',
	'login': 'Inicia sesión',
	'generate new token': 'Generar nuevo token',
	'change e-mail': 'Cambiar correo',
	'production company': 'Compañia de producción',
	'delete project': 'Eliminar proyecto',
	'are you sure to delete this project?': '¿Estás seguro de eliminar este proyecto?',
	'legal terms': 'Términos legales',
	'data policy': 'Política de datos',
	'copyright  © 2022 grupo cincoveinticinco sas. all rigths reserved': 'Derechos de autor © 2022 grupo cincoveinticinco sas. Todos los derechos reservados',
	'log out': 'Cerrar sesión',
	'spanish': 'Español',
	'portuguese': 'Portugués',
	'english': 'Inglés',
	'new': 'Nuevo',
	'closed': 'Cerrado'


}