export const TRANSLATE_PT: any = {
	'incidents': 'Incidentes',
	'date': 'Encontro',
	'add incident': 'Adicionar incidente',
	'all centers': 'Todos os centros',
	'centers': 'Centros',
	'add project': 'Adicionar projeto',
	'production Company': 'Companhia de produção',
	'project': 'Projeto',
	'season': 'Estação',
	'center': 'Centro',
	'location': 'localização',
	'users': 'Usuários',
	'open inc': 'Inc. abertos',
	'closed inc': 'Inc. cerrados',
	'no data found': 'Nenhum dado encontrado',
	'merge': 'Mesclar',
	'project name': 'Nome do Projeto',
	'abbreviation': 'Abreviação',
	'add': 'Adicionar',
	'delete': 'Excluir',
	'email': 'Correo',
	'save': 'Salve',
	'project users': 'Usuários do projeto',
	'search': 'Procurar',
	'insert': 'Inserir',
	'projects': 'Projetos',
	'all statuses': 'Todos os status',
	'all types': 'Todos os tipos',
	'all projects': 'Todos os projetos',
	'clear': 'Límpido',
	'reference': 'Referência',
	'status': 'Status',
	'incident type': 'Tipo de incidente',
	'not assigned': 'Não atribuído',
	'incident': 'Incidente',
	'comments': 'Comentários',
	'edit incident': 'Editar incidente',
	'select option': 'Selecione a opção',
	'how do you want to report the incident?': 'Como você deseja relatar o incidente?',
	'anonymous': 'Anônimo',
	'i want to identify myself': 'Eu quero me identificar',
	'do you authorize us to send messages to your email that maybe required for the investigation?': 'Você nos autoriza a enviar mensagens para seu e-mail que talvez sejam necessárias para a investigação?',
	'yes': 'Sim',
	'confirm email': 'Confirmar email',
	'first name': 'Primeiro nome',
	'name': 'Nome',
	'last name': 'Sobrenome',
	'country': 'País',
	'phone number': 'Número de telefone',
	'number': 'Número',
	'select issue type': 'Selecione o tipo de problema',
	'what is the production?': 'Qual é a produção?',
	'production Name': 'Nome de produção',
	'please describe the incident': 'Por favor descreva o incidente',
	'description': 'Pescrição',
	'people involved in the incident': 'Pessoas envolvidas no incidente',
	'people': 'Pessoas',
	'date and location of the incident': 'Data e local do incidente',
	'has this incident happened more than once?': 'Esse incidente aconteceu mais de uma vez?',
	'please provide the details': 'Por favor, forneça os detalhes',
	'details': 'Detalhes',
	'have you discussed this incident with your manager or production supervisor?': 'Você discutiu este incidente com seu gerente ou supervisor de produção?',
	'who did you report this incident to?': 'Para quem você denunciou esse incidente?',
	'who': 'Quem',
	'cancel': 'Cancelar',
	'under review': 'Sob revisão',
	'on': 'Sobre',
	'response': 'Resposta',
	'date report': 'Relatório de data',
	'method': 'Método',
	'reporter': 'Repórter',
	'notifications': 'Notificações',
	'position on production': 'Posição sobre a produção',
	'date incident': 'Data do incidente',
	'location incident': 'Incidente de localização',
	'repeated incident': 'Incidente repetido',
	'discussed incident with manager or supervisor': 'Discutiu o incidente com o gerente ou supervisor',
	'responses': 'Respostas',
	'write your response': 'Escreva sua resposta',
	'admin module': 'Módulo de administração',
	'login with google acount': 'Login com conta do google',
	'login with other email': 'Entrar com outro e-mail',
	'new project': 'Novo projeto',
	'token successfully generated': 'Token gerado com sucesso',
	'please check your email': 'Por favor verifique seu email',
	'login': 'Conecte-se',
	'generate new token': 'Gerar novo token',
	'change e-mail': 'Mude o e-mail',
	'production company': 'Companhia de produção',
	'delete project': 'Excluir projeto',
	'are you sure to delete this project?': 'Você tem certeza de excluir este projeto?',
	'legal terms': 'Termos legais',
	'data policy': 'Política de dados',
	'copyright  © 2022 grupo cincoveinticinco sas. all rigths reserved': 'Direito autoral © 2022 grupo cincoveinticinco sas. Todos os direitos reservados',
	'log out': 'Fechar Sessão',
	'spanish': 'Espanhol',
	'portuguese': 'Português',
	'english': 'Inglês',
	'new': 'Novo',
	'closed': 'Fechado'


}